name: Deploy to Local Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to /var/www
        run: |
          echo "Deploying files to /var/www..."
          sudo rm -rf /var/www/*
          sudo cp -r . /var/www/
          sudo chown -R www-data:www-data /var/www
          echo "Deployment complete!"
